### ISSUE TITLE
minispec.org is down

### ISSUE THREAD

**Issue by vindarel** [lamberta/minispec#8]
Hello,

just discovering this project but its website is down, maybe from some time already…

Would it be hostable on github pages ?

**Comment by lamberta** [comment]
Thanks. Updated the project description URL to its github hosting: https://lamberta.github.io/minispec/

The site was met with mixed results when I released it, so I haven't done much with it since. I keep it around because I found it helpful when learning, but it's not worth the domain fee to me.

**Comment by vindarel** [comment]
it's a nice resource, I don't know why I didn't stop over it before. I re-wrote some content that we find there on the Cookbook. Maybe it's a bit raw for beginners. Anyway, thanks !
